# Build customization
builds:
  - binary: terraform-provider-servicenow
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386

# Archive customization
archives:
-
  format: zip

  replacements:
    amd64: 64-bits
    386: 32-bits
    darwin: macOS

  files:
    - nothing.*
    